# Generated by Django 4.1.7 on 2023-03-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_img', models.ImageField(default='default/img.png', upload_to='')),
                ('about_img', models.ImageField(default='default/img.png', upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('degree', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('brithday', models.DateTimeField()),
                ('experience', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('frilance', models.CharField(choices=[('Available', 'Available'), ('None', 'None')], default='None', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('text', models.TextField()),
            ],
        ),
    ]
