# Generated by Django 4.1.7 on 2023-03-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='frilance',
            field=models.CharField(choices=[('', 'Available'), ('None', 'None')], default='None', max_length=15),
        ),
    ]
