# Generated by Django 4.1.7 on 2023-03-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blog_frilance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='frilance',
            field=models.CharField(choices=[('', 'Available'), ('', 'None')], default='', max_length=15),
        ),
    ]
