# Generated by Django 4.1.7 on 2023-03-16 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_category_images_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='img',
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.portfolio'),
            preserve_default=False,
        ),
    ]
