# Generated by Django 4.1.7 on 2023-03-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_portfolio_img_images_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='product',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='images',
            field=models.ManyToManyField(to='home.images'),
        ),
    ]
