# Generated by Django 4.1.7 on 2023-03-24 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_images_product_portfolio_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='images',
        ),
        migrations.AddField(
            model_name='images',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.portfolio'),
            preserve_default=False,
        ),
    ]
