# Generated by Django 4.2.1 on 2023-05-25 07:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=84)),
                ('img', models.ImageField(upload_to='about_img/')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='BaseNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('fab fa-facebook-f', 'Facebook'), ('fa-brands fa-instagram', 'Instagram'), ('fa-brands fa-telegram', 'Telegram'), ('fa-brands fa-github', 'Github'), ('fab fa-youtube', 'Youtube'), ('fa-brands fa-linkedin', 'LinkedIn'), ('fab fa-twitter', 'Twitter'), ('fab fa-dribbble', 'Web')], max_length=80)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('option', models.CharField(choices=[('fikr', 'Fikr-Mulohaza'), ('ijobiy', 'Ijobiy'), ('salbiy', 'Salbiy'), ('ish', 'Ish'), ('shaxsiy', 'Shaxsiy')], max_length=30)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('img', models.ImageField(upload_to='portfolio')),
                ('description', ckeditor.fields.RichTextField()),
                ('github_link', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('view', models.PositiveBigIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.category')),
                ('coloborator', models.ManyToManyField(to='portfolio.network')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='portfolio/img')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tag',
            field=models.ManyToManyField(to='portfolio.tag'),
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=60, null=True)),
                ('title2', models.CharField(blank=True, max_length=60, null=True)),
                ('header_buy', models.CharField(blank=True, max_length=30, null=True)),
                ('header_buy_hover', models.CharField(blank=True, max_length=30, null=True)),
                ('title_discription', models.CharField(blank=True, max_length=255, null=True)),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='head_img')),
                ('title_footer', models.CharField(blank=True, max_length=80, null=True)),
                ('title_footer_link', models.URLField(blank=True, null=True)),
                ('title_footer_hover', models.CharField(blank=True, max_length=80, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('portfolio_h3', models.CharField(blank=True, max_length=60, null=True)),
                ('portfolio_h2', models.CharField(blank=True, max_length=60, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.network')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_header', models.ImageField(upload_to='')),
                ('contact_about', models.CharField(max_length=800)),
                ('location', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=50)),
                ('contact_link', models.URLField()),
                ('contact_name', models.CharField(max_length=60)),
                ('follow', models.ManyToManyField(to='portfolio.basenetwork')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('body', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfolio')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.comment')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, default='web_icon/ali3.jpg', upload_to='web_icon')),
                ('title', models.CharField(blank=True, default='Base Title', max_length=255)),
                ('header_network_header', models.CharField(default='Ijtimoiy havolalar:', max_length=60)),
                ('copyright', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright', to='portfolio.network')),
                ('header_network', models.ManyToManyField(related_name='header_network', to='portfolio.network')),
                ('network', models.ManyToManyField(related_name='basenetwork', to='portfolio.basenetwork')),
            ],
        ),
    ]
