# Generated by Django 4.1.7 on 2023-05-06 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('<i class="fab fa-facebook-f">', 'Facebook'), ('fa-brands fa-instagram', 'Instagram'), ('<i class="fa-brands fa-telegram" style="color: #2474ff;"></i>', 'Telegram'), ('<i class="fa-brands fa-github"></i>', 'Github'), ('<i class="fab fa-youtube"></i>', 'Youtube'), ('<i class="fa-brands fa-linkedin" style="color: #326dd2;"></i>', 'LinkedIn'), ('<i class="fab fa-twitter"></i>', 'Twitter'), ('<i class="fab fa-dribbble"></i>', 'Web')], max_length=80)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=60)),
                ('title2', models.CharField(max_length=60)),
                ('title3', models.CharField(max_length=60)),
                ('title_discription', models.CharField(max_length=255)),
                ('head_img', models.ImageField(upload_to='head_img')),
                ('title_footer', models.CharField(max_length=80)),
                ('title_footer_link', models.URLField()),
                ('title_footer_hover', models.CharField(max_length=80)),
                ('subtitle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('img', models.ImageField(upload_to='portfolio')),
                ('description', models.TextField()),
                ('github_link', models.URLField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, default='web_icon/ali3.jpg', upload_to='web_icon')),
                ('title', models.CharField(blank=True, default='Base Title', max_length=255)),
                ('copyright', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright', to='portfolio.network')),
                ('network', models.ManyToManyField(related_name='basenetwork', to='portfolio.basenetwork')),
            ],
        ),
    ]
