# Generated by Django 4.1.7 on 2023-05-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenetwork',
            name='icon',
            field=models.CharField(choices=[('fab fa-facebook-f', 'Facebook'), ('fa-brands fa-instagram', 'Instagram'), ('fa-brands fa-telegram', 'Telegram'), ('fa-brands fa-github', 'Github'), ('fab fa-youtube', 'Youtube'), ('fa-brands fa-linkedin', 'LinkedIn'), ('fab fa-twitter', 'Twitter'), ('fab fa-dribbble', 'Web')], max_length=80),
        ),
    ]
