# Generated by Django 4.1.7 on 2023-05-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_basenetwork_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='header_network',
            field=models.ManyToManyField(blank=True, null=True, related_name='header_network', to='portfolio.network'),
        ),
    ]
