# Generated by Django 4.1.7 on 2023-05-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_base_header_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='header_network_header',
            field=models.CharField(default='Ijtimoiy havolalar:', max_length=60),
        ),
    ]
