# Generated by Django 4.1.7 on 2023-05-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_base_header_network_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.network'),
        ),
    ]
