# Generated by Django 4.1.7 on 2023-05-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_index_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='portfolio_h3',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
