# Generated by Django 4.1.7 on 2023-05-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_index_title3_index_header_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='coloborator',
            field=models.ManyToManyField(to='portfolio.network'),
        ),
    ]
