# Generated by Django 4.1.7 on 2023-05-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_portfolio_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio.tag'),
        ),
    ]
