# Generated by Django 4.1.7 on 2023-05-09 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_tag_portfolio_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('body', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.comment')),
            ],
        ),
    ]
