# Generated by Django 4.1.7 on 2023-05-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='view',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
