# Generated by Django 4.1.7 on 2023-05-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_portfolio_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
