# Generated by Django 4.1.7 on 2023-05-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('option', models.CharField(choices=[('fikr', 'Fikr-Mulohaza'), ('ijobiy', 'Ijobiy'), ('salbiy', 'Salbiy'), ('ish', 'Ish'), ('shaxsiy', 'Shaxsiy')], max_length=30)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_header', models.ImageField(upload_to='')),
                ('contact_about', models.CharField(max_length=800)),
                ('location', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('follow', models.ManyToManyField(to='portfolio.basenetwork')),
            ],
        ),
    ]
