# Generated by Django 4.1.7 on 2023-05-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_contact_msg_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
