# Generated by Django 4.1.7 on 2023-05-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_remove_contact_email_contact_contact_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
