# Generated by Django 4.1.7 on 2023-05-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='tag',
            field=models.ManyToManyField(to='portfolio.tag'),
        ),
    ]
