# Generated by Django 4.1.7 on 2023-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_alter_portfolio_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='header_network',
            field=models.ManyToManyField(related_name='header_network', to='portfolio.network'),
        ),
    ]
