# Generated by Django 4.1.7 on 2023-05-18 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_alter_portfolio_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='portfolio/img')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfolio')),
            ],
        ),
    ]
